### ISSUE TITLE
FYI: RNifti package

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsR#112]
Just FYI - the RNifti package has implemented a similar pointer structure for NIfTI files if you find it relevant: https://github.com/jonclayden/RNifti

**Comment by stnava** [comment]
cool.  @cookpa  @jeffduda this may be relevant to better understanding or resolution of https://github.com/stnava/ANTsR/issues/111

**Comment by dorianps** [comment]
I was thinking the same. I would guess this package has the same gc()
issue. :)

**Comment by cookpa** [comment]
Same issue for me on our cluster, with `gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)`.

Memory is released after a `gc()`

Still, this package will be useful. It lets you have direct access to the header, which is great. And because it doesn't have the compatibility overhead of ITK I/O, it should be more flexible in what it will let you do (eg, qform != 2).

**Comment by stnava** [comment]
right - just to be clear, antsr i/o supports many more file formats than nii:

```
    NiftiImageIO
    NrrdImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    GDCMImageIO
    BMPImageIO
    LSMImageIO
    PNGImageIO
    TIFFImageIO
    VTKImageIO
    StimulateImageIO
    BioRadImageIO
    MetaImageIO
    MRCImageIO
    GE4ImageIO
    GE5ImageIO
    MGHImageIO
```

this need for multiple I/O type compatibility is the **first** reason why we (ITK community) cannot support affine transformations in the header.   the **second** reason is that even basic operations would not be correctly implemented unless they included the affine tx which would induce massive overhead.  we discussed these issues years ago in the itk development process and, as such, it is how it is.

**Comment by cookpa** [comment]
Thanks for the explanation. I wasn't suggesting changing anything, ITK is the way it is for good reasons.

I envision using RNifti either independently of ANTsR, or to import / export ANTsR data, where headers might need modifying to maintain compatibility with different software. 

Again to be clear, this is to be avoided where possible because tinkering with headers is painful and risky. But sometimes a necessary evil.
