### ISSUE TITLE
Install issue on ANTsR.

### ISSUE THREAD

**Issue by taposh** [stnava/ANTsR#136]
Hi,

I am facing error in installing ANTsR package. I am on MacOS.  Any pointers would help.

Command used to install:
devtools::install_github("stnava/ANTsR")

1 warning generated.
cd /private/var/folders/46/zm1hrxpx0qxd1phxpr931fr40000gr/T/RtmpUgkg22/devtools1113a10bb7a42/stnava-ANTsR-69936eb/src/antb && make -j 2
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [libs] Error 2
ERROR: compilation failed for package ‘ANTsR’

**Comment by stnava** [comment]
do you have cmake or cmaker installed in your environment?


brian

**Comment by stnava** [comment]
you might also read the installation section here:

http://stnava.github.io/ANTsR/

the one that says "please read this entire section"


brian

**Comment by justbennet** [comment]
I am seeing the same error message.  I am on CentOS 7, with cmake version 2.8.12.2 from the system.  I have R 3.4.1 freshly compiled from source.  I ran

install.packages('Rcpp')
install.packages('tools')
install.packages('methods')
install.packages('magrittr')

Though both 'tools' and 'methods' complain they are unavailable and are part of 'base' now.

I also install devtools, and I am using Method 1, with devtools in R

> library(devtools)
> install_github('stnava/ANTsR')

All of the following appear to install and load successfully:

```
$ ls /sw/arcts/centos7/ANTsR/3.4
abind  ITKR  magic  magrittr  mnormt  psych  Rcpp  RcppEigen  rsvd
$ R --quiet
> library(abind)
> library(ITKR)
> library(magic)
> library(magrittr)
> library(mnormt)
> library(psych)
> library(Rcpp)
> library(RcppEigen)
> library(rsvd)
>
```
I have access to cmake 3.5.2 if the problem is that cmake is too old.  I am installing these into the folder defined by the environment variable R_LIBS_SITE.

ANTsR compiles successfully, but it fails when preparing for lazy loading with the undefined symbol message.  I found something on the web suggesting that symbol might be in GDCM, so I have /sw/arcts/centos7/GDCM-2.8.2-Linux-x86_64/lib in my LD_LIBRARY_PATH when I start R, but it was not there when I compiled R.

Those libraries are stripped, but I find

```
$ for lib in *.so ; do     echo $lib;     strings $lib | grep gdcmjpeg16_jpeg_resync_to_restart; done
libgdcmcharls.so
libgdcmCommon.so
libgdcmDICT.so
libgdcmDSED.so
libgdcmexpat.so
libgdcmIOD.so
libgdcmjpeg12.so
libgdcmjpeg16.so*
gdcmjpeg16_jpeg_resync_to_restart
libgdcmjpeg8.so
libgdcmmd5.so
libgdcmMEXD.so
libgdcmMSFF.so*
gdcmjpeg16_jpeg_resync_to_restart
libgdcmopenjp2.so
libgdcmuuid.so
libgdcmzlib.so
libsocketxx.so
```

If you have any insight, I would appreciate it.

Thanks,  -- bennet
