### ISSUE TITLE
Propagation method in iMath('PropagateLabelsThroughMask')

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#143]
I am using `iMath('PropagateLabelsThroughMask')` and seem to be working well. Looks like there is a parameter one can choose there, which sets the propagation method. The code seem to accept values < 3, but I can't seem to find any documentation what the methods are. 

@jeffduda  or @cookpa , any idea on this? Wasn't this the function Phil added some months ago? Can't find his email though.

Thanks

**Comment by stnava** [comment]
this paper describes the methods:

https://www.ncbi.nlm.nih.gov/pubmed/21118779

0 - no constraint

1 - well-composedness

2 - topological constraint

and from ImageMath

  PropagateLabelsThroughMask: Final output is the propagated label image.
Optional stopping value: higher values allow more distant propagation

      Usage        : PropagateLabelsThroughMask
speed/binaryimagemask.nii.gz initiallabelimage.nii.gz
Optional-Stopping-Value  0/1/2


similar info in

```

iMath( 0 , "GetOperationsFull" )

```


brian

**Comment by dorianps** [comment]
Just a quick report. At least in my situation methods 1 and 2 do not produce better results. Here is an example of 360 labels originally located in the cortex only and being propagated towards the white matter.


Starting labels:
![image](https://cloud.githubusercontent.com/assets/9083517/24889640/2112391c-1e39-11e7-9b19-e35adfa873c8.png)

No constraint:
![image](https://cloud.githubusercontent.com/assets/9083517/24889656/3337a8a2-1e39-11e7-9c14-1f4d07a7c247.png)

Well composedness:
![image](https://cloud.githubusercontent.com/assets/9083517/24889613/017b6bf0-1e39-11e7-9263-a3a663edea9a.png)

**Comment by cookpa** [comment]
The function I added was called multiLabelMorphology, and differs from PropagateLabelThroughMask. It does morphology operations independently on each label, preserving the original labels. It works but could be made much faster by using ITK's optimized multilabel operations.

PropagateLabelThroughMask uses a fast marching method to compute which label should propagate to unlabeled voxels within a mask. It also preserves the original labels, but instead of applying a fixed dilation or closing, it fills the unlabeled voxels until a stopping criteria is met.
