### ISSUE TITLE
Manual iteration improves registration results in ANTsR

### ISSUE THREAD

**Issue by caileyfitz** [stnava/ANTsR#144]
I am very new to ANTsR and image registration in general. I am working with a dataset of brain images that I would like to register to a template. 

Currently, upon first call of antsRegistration, I am getting a mutual information value of ~.66:
~~~
mytx1<-antsRegistration(fixed=fi,moving=mi,typeofTransform=c('SyN'))
miwarp1 <-antsApplyTransforms(fixed=fi,moving=mi,transformlist=mytx$fwdtransforms
~~~

I am able to iterate upon that by calling antsRegistration 19 more times. The call is roughly of the form (not in R syntax but rather a simplification for this purpose): 
~~~
for ii=2:20{
mytx_ii<-antsRegistration(fixed=fi,moving=miwarp_(ii-1),typeofTransform=c('SyN'))
miwarp_ii <-antsApplyTransforms(fixed=fi,moving=miwarp_(ii-1),
            transformlist=mytx_ii$fwdtransforms
}
~~~

Each time I iterate, I get a mutual information value that is better than the last (e.g. after 19 additional iterations, my MI value is ~.87). **But shouldn't each registration call be minimizing the mutual information metric without the need for me to manually iterate?** Is there some way in R for me to specify a MI cutoff value or set a number of iterations? I know that you can do that with the command-line version of ANTs, but I do not understand bash scripting at all, so that's why I have been using ANTsR. 

Any help would be greatly appreciated!

**Comment by cookpa** [comment]
The default iterations for `antsRegistration` are `regIterations = c(40, 20, 0)`. Try adding something like `regIterations = c(40,60,10)` to the function call.

**Comment by cookpa** [comment]
I would also check that the affine part of the registration worked well. You can do this by using antsApplyTransforms with just the affine part:

```
warped <-antsApplyTransforms(fixed=fix,moving=mov, transformlist=mytx$fwdtransforms[2])
```

If this looks like it can be improved, you can run antsRegistration with typeofTransform = "Affine" and customize the affine registration. You can then pass that to a `SyNOnly` registration as `initialTransform`.

Though this runs two sets of registrations, it is not the same as the loop you had above, because the input to antsRegistration is always the same fixed and moving image. We only initialize the transform from the previous step. This way we are always running the registration on the original data, and the final transform is applied to the original data at the end of the process. Thus the input image only ever gets resampled one time, which is a good thing to avoid accumulating interpolation errors.

**Comment by stnava** [comment]
thanks @cookpa


brian

**Comment by dorianps** [comment]
Cailey, since you are new, note that the best registration in ANTsR is
SyNCC, not SyN. It takes much longer but if you are trying to get the most
optimal registration that's the way to go.

Dorian

**Comment by ntustison** [comment]
Hi Cailey,

We like to informally keep track of groups who use ANTs/ANTsR and it would seem you're at UVa as well.  You might be interested in the [ANTs/ANTsR workshop](http://cal.hsl.virginia.edu/event/3190203) we're having next month.

Nick

**Comment by caileyfitz** [comment]
@cookpa Thank you for the help! By increasing iterations, I was able to get a better mutual information value the first time, although it looks like even that has its limits. I tried  `regIterations = c(90,70,50)` and went from `MI=.66` with the default number of iterations to `MI=.72` with the custom number of iterations. If I wanted a higher MI value, would I just continue to increase the iteration number? I will also check the affine part of the registration to see if that is where the trouble is occurring. 

@dorianps Thanks for this heads up! I ran registration with SyNCC and was getting similar mutual information values as when I was running SyN, but, as you noted, SyNCC takes significantly longer. That's why I opted for just SyN. I know that there is `antsImageMutualInformation` to check the MI metric, but I am not seeing an equivalent test for CC in the ANTsR manual. 

@ntustison I am indeed at UVA. I just signed up for the workshop! Thanks for bringing it to my attention.

**Comment by suppechasper** [comment]
@caileyfitz 
Old thread but since nobody mentioned it it might be worth adding here:

1. note that by iterating you allow a less regularized warp. I.e. every time you start from an already warped image the regularization from the previous warp is discarded and you allow for further transformation.
2. Depending on how SyN is implemented the flow is a concatenation of N vector fields. By iteratively updating you essentially have a finer discretization of the flow.

I guess together those would ultimately allow for an almost perfect match, which is probably not what you were aiming for.
