### ISSUE TITLE
Unused functions

### ISSUE THREAD

**Issue by bkandel** [stnava/ANTsR#30]
In advance of the CRAN submission, it would be nice to pare down the functions to emphasize the core utility.  Including functions in CRAN submissions implies a commitment to maintaining the function for the foreseeable future.  Here is a list of functions that look to me like they either duplicate functionality or can be deleted: 
maskImage
quantifySNPs (useful, but not sure it's suitable for ANTsR)
filterfMRIForNetworkAnalysis (overlap with frequencyFilterfMRI? is this still used?) 
exemplarInpainting vs. basicInPainting  -- why have both?  Shouldn't we just have inPaint and have methods for exemplar and basic inpainting? 
jointIntensityFusion and ""3D:  Why have two functions for different dimensionalities? 
renderNetwork and plotBasicNetwork:  Can these be combined? 
smoothImage -- I have always thought this should be part of iMath.  Is there a consensus on this?  Would this be too annoying? 
visualizeBlob -- looks to me like it's been superseded by the various rendering functions.

**Comment by stnava** [comment]
quick comments

* maskImage - i think this is convenient because of

```
       myimg.mask <- maskImage(myimg, mylab, list( 1,  3, 9 ) )
```
though this option is not clear from the parameter list
* quantifySNPs - useful for dim red applications in genomics
* filterfMRIForNetworkAnalysis - several possible dependencies in [documentation/tutorials](http://rpubs.com/stnava/ANTsTut) not sure of difference with antsBOLDNetworkAnalysis, latter probably better validated but not sure ... undecided
* exemplarInpainting vs. basicInPainting - two different algorithms with different api
* jointIntensityFusion/3D - need both for reasons of efficiency: specialized slice by slice for 3D dramatically reduces memory ... would be fantastic to generalize this if possible
* renderNetwork - has already been eliminated
* smoothImage calls iMath ... should be reworked ... and could be added to iMath ... all calls to this function would have to be replaced ... it should be extended with median filtering as well
* visualizeBlob - i would be fine if this went away

**Comment by bkandel** [comment]
I added that example to maskImage and clarified documentation and deleted visualizeBlob.
