### ISSUE TITLE
SyN failure?

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#73]
I think I had this experience before, and here it is presenting again. A SyN registration of a lesioned brain using a mask, fails and outputs the template instead of the registered brain.

Attached are the files. 
https://github.com/stnava/ANTsR/files/98679/SyNfailureexample.zip

Can someone give it a try, takes only 5mins. When I plot the registered brain it simply shows the template:

![image](https://cloud.githubusercontent.com/assets/9083517/12469281/95c35e16-bfb8-11e5-97e7-7ca5ae4cc020.png)

**Comment by cookpa** [comment]
The link appears broken. Is code there too? One possible cause is recycling of R vector elements.

**Comment by stnava** [comment]
use the verbose option to see more about what is happening.  likely there is some issue with the initial overlap or something like that.

**Comment by stnava** [comment]
also - you can attach files directly ... e.g. as i've done here.
[temp_this_is_a_nifti_img.zip](https://github.com/stnava/ANTsR/files/98588/temp_this_is_a_nifti_img.zip)

**Comment by dorianps** [comment]
Yes, code is there too. Strange, I can open the link from both browsers.

Tried to put the zip here, but it did not take it. Now seems to be working from my laptop.
[SyNfailureexample.zip](https://github.com/stnava/ANTsR/files/98679/SyNfailureexample.zip)

**Comment by dorianps** [comment]
Ahh, the code is not defining the registration type. Please add this at the beginning:
regtypes=c('SyN'); z=1
or just explicitly typeofTransform = 'SyN' in the antdRegistration call

**Comment by cookpa** [comment]
With verbose=T, I get:

*** Running SyN registration (varianceForUpdateField = 3.0000e+00, varianceForTotalField = 0.0000e+00) ***

Exception caught: 
itk::ExceptionObject (0x7feef3f20098)
Location: "unknown" 
File: /Users/pcook/Library/R/3.2/library/ITKR/libs/include/ITK-4.9/itkMattesMutualInformationImageToImageMetricv4.hxx
Line: 430
Description: itk::ERROR: MattesMutualInformationImageToImageMetricv4(0x7feef3eef3f0): Too many samples map outside moving image buffer. There are only 9362 valid points out of 180224 total points. The images do not sufficiently overlap. They need to be initialized to have more overlap before this metric will work. For instance, you can align the image centers by translation.


The output is then as you describe, the warped (fixed, moving) images are just the unwarped (moving, fixed) images. This is how they are initialized in antsRegistration.R :

  https://github.com/stnava/ANTsR/blob/master/R/antsRegistration.R#L96-L97

I guess this is done so that the correct image dimensions are allocated for the warped images. If registration works, the contents of the images get replaced with the warped output. But if registration fails it just swaps the input and you won't know unless you look at the images.

**Comment by muschellij2** [comment]
Also, the transformations would not exist but a transform list comes out,
so you can check the existence of those files

**Comment by dorianps** [comment]
This will mean more code to check when a registration fails.

About the error, what is the solution here? Doesn't SyN initialize itself by matching center of masses or something like that?

Ty.

**Comment by cookpa** [comment]
Yes, it looks for an initial transform, and if that doesn't exist, it passes "-r [ fixed, moving, 1]" to the call to antsRegistration.

The failure comes at the SyN stage, so maybe the affine part went wrong, leading to insufficient overlap inside the masked region.

**Comment by dorianps** [comment]
I know ITK works in physical space, but just to through it there, this image has an unusual orientation compared to my other images:

> antsGetDirection(strokt1)
     [,1] [,2] [,3]
[1,]    0    0   -1
[2,]    1    0    0
[3,]    0    1    0

Perhaps this might contribute to the problem.

**Comment by cookpa** [comment]
Maybe, if there is doubt I usually open images in two SNAP windows and click around to see how the header is being interpreted.

**Comment by stnava** [comment]
this is an interesting case and i'm surprised it has not come up before in @dorianps work.   the mask covers about half of the brain.  that is probably leading to sub-optimal affine mapping, as suggested by @cookpa  ... my recommendation here is to use standard rigid+affine mapping, then follow this with deformable registration.  and try this *in both directions* i.e. template to stroke and the reverse as well ( two different affine maps ).   in one case ( with template as fixed ), transform the mask to the template and then run the newly added SyNOnly ... this should help debug this issue more efficiently.  it is possible there is some bug with how the mask is being used/indexed ... but need to drill down a bit more.

**Comment by ntustison** [comment]
Hi all,

Are you using the latest ANTs?  I'm asking because, if Phil is correct, this [issue](https://github.com/stnava/ANTs/issues/254) might be relevant which was, as you can see, only recently fixed.

Nick

**Comment by stnava** [comment]
here is an example that is suggestive:

```
library (ANTsR )
mask.lesion=antsImageRead('mask.lesion.nii.gz')
template=antsImageRead('template.nii.gz')
strokt1=antsImageRead('strokt1.nii.gz')
strokt1reg=antsRegistration(
  fixed=template,
  moving=strokt1,
  typeofTransform = "Affine",verbose=TRUE )
aff = strokt1reg$fwdtransforms
maskaff = antsApplyTransforms(
  fixed=template, mask.lesion, transformlist=aff, whichtoinvert=c(TRUE) )
strokt1reg=antsRegistration(
    initialTransform=aff,
    moving=strokt1,
    fixed=template, mask=maskaff,
    typeofTransform = "SyNOnly",verbose=TRUE )
```

following up on this kind of experiment could help determine if this suggests an implementation bug in terms of how the points are queried in the mask or, alternatively, how the mask is used by ANTsR.

i will update the ants version in ANTsR to see if @ntustison is correct ...

**Comment by dorianps** [comment]
I have updated ANTsR after that issue in ANTs was resolved. Maybe the fix needs to propagate to ANTsR as well.

**Comment by stnava** [comment]
ANTsR was using a commit from Jan 14 .

**Comment by stnava** [comment]
another example ... i think this suggests an issue with how the mask's valid points are being computed.  because this fails:

```
mask.lesion=antsImageRead('mask.lesion.nii.gz')
template=antsImageRead('template.nii.gz')
strokt1=antsImageRead('strokt1.nii.gz')
strokt1aff=antsRegistration(
  moving=template,
  fixed=strokt1,
  typeofTransform = "Affine",verbose=TRUE )
# this mapping should work
strokt1reg=antsRegistration(
  moving=strokt1aff$warpedmovout,
  fixed=strokt1, mask=mask.lesion,
  typeofTransform = "SyNOnly",verbose=TRUE )
# but does not
```

while my previous example works.  but someone may want to try a similar thing outside of ANTsR.

**Comment by ntustison** [comment]
If nobody else looks at it outside of ANTsR, I'll be sure to do it.  I have to head into Irvine today so I'll have some time.

**Comment by dorianps** [comment]
Thank you all for looking into this. While we are here, can I suggest that registration fails with an error message if it fails. The way it is now can be very misleading. I have basically run hundreds of  registrations and now I have doubts that some of them may have been wrong without noticing.

A stop() call should be sufficient to make the function (and the scripts) fail in order for the user to understand that something did not work.

**Comment by stnava** [comment]
done this morning


brian

**Comment by cookpa** [comment]
I think it does have to do with the mask. On the command line:

moving=template.nii.gz
fixed=strokt1.nii.gz 

antsRegistration -d 3 -r [ $fixed, $moving, 1] -m mattes[ $fixed, $moving, 1, 32, Regular, 0.2 ] -t Affine[0.25] -c 2100x1200x1200x0 -s 3x2x1x0 -f 4x2x2x1 -m mattes[ $fixed, $moving, 1, 32] -t SyN[0.25, 3, 0] -c 2100x1200x1200x0  -s 3x2x1x0 -f 4x2x2x1 -u 1 -z 1 -o [ output_ , movingWarped.nii.gz, fixedWarped.nii.gz] -x mask.lesion.nii.gz -v 1

This fails, but if I run just the affine part, it looks like a decent match. If I change the order of fixed and moving images 

moving=strokt1.nii.gz 
fixed=template.nii.gz 

antsRegistration -d 3 -r [ $fixed, $moving, 1] -m mattes[ $fixed, $moving, 1, 32, Regular, 0.2 ] -t Affine[0.25] -c 2100x1200x1200x0 -s 3x2x1x0 -f 4x2x2x1 -m mattes[ $fixed, $moving, 1, 32] -t SyN[0.25, 3, 0] -c 2100x1200x1200x0  -s 3x2x1x0 -f 4x2x2x1 -u 1 -z 1 -o [ output_ , movingWarped.nii.gz, fixedWarped.nii.gz] -x [NA, mask.lesion.nii.gz] -v 1

appears to work - at least it doesn't crash immediately, I haven't run SyN all the way through and checked the results.

I'm not sure how to pass a moving image mask in ANTsR.

**Comment by ntustison** [comment]
Hey Brian, I don't know if you considered this in writing [antsRegistration.R](https://github.com/stnava/ANTsR/blob/master/R/antsRegistration.R#L132-L140.) but after concatenating the antsRegistration command it seems you add a mask (if specified by the user).  It seems that for this particular situation, I'm guessing, one might want to use the mask only for the SyN stage.  If that's the case, you can simply add ``-x [none,none]`` for such stages. 

If one simply dilates the original lesion mask to get a few more points in the mask, then the example works calling the antsRegistration.cxx program.

**Comment by stnava** [comment]
@ntustison - thx!   @dorianps  ( and anyone else ) -  does that seem like the most common / useful default behavior?  i.e. only use the mask at the deformable step?    i will think about if there is a way to implement with an easy switch between both options ...

**Comment by dorianps** [comment]
I am not sure I understand the problem. Is the issue at the Affine stage? Why would it be ok to use the mask only for deformations, isn't it important for Affine as well? Or is this just a workaround to resolve the bug?

Frankly I don't even understand why a few voxels more in the mask fix things. There are already plenty of voxels that fall on the healthy areas of the strokt1 image.

**Comment by stnava** [comment]
i think the basic problem is that there is an adhoc check ( in ITK for a
long time and which i've never liked ) that tries to deal with Mattes-MI's
need for a sufficient number of samples to estimate the joint histogram.
 this mask is small enough ( presumably relative to the image domain ) that
it is borderline wrt the ad-hoc check.


brian

**Comment by dorianps** [comment]
So this means one cannot use a mask that is a quarter of the brain?

**Comment by cookpa** [comment]
I think Brian is correct:

https://github.com/InsightSoftwareConsortium/ITK/blob/285d589717dcb5252e68b90241b9c4853aa6319b/Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx#L231

The number of valid points needs to be at least (total points) / 16. In this case, the error is saying there are 9362 valid points out of 180224 (the size of the fixed image at shrink factor 4), which is close to the limit. So it makes sense that dilating the mask a bit will help in this case.

The affine registration seems to work so most of the points probably are inside the domain of the fixed image, but they are not counted as valid because they are not in the masked region.

**Comment by ntustison** [comment]
Hey Brian,

I'm guessing Michael put that in there but if you want to change that, I can easily make that change and put it on gerrit for review.

**Comment by stnava** [comment]
yes - we copied this from the original mattes - the question is how to
define the basic "valid points" which is ( i think ) returned by

` const SizeValueType numberOfPoints = this->GetNumberOfDomainPoints(); `

which phil pointed out ... that ndomainpoints should probably be the size
of the mask ( instead of defined by the size of the domain, as currently ).
still just guessing as i have not checked the code.


brian

**Comment by dorianps** [comment]
Hi guys, any news on this problem. I am holding back to try something.

A partially related topic is the possibility to have graded masks. I was told by @stnava that masks *must* be binary. Is there any possibility to enable graded masks in the future, or is it too complicated? The idea would be to have all regions/voxels contribute to the registration, but at different amounts.

**Comment by ntustison** [comment]
I don't think we've settled on a specific solution.  Since any solution would have to go through ITK approval, I would try working around it in the short term.

The B-spline registration method classes can take a weighted mask (see, e.g. [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/RegistrationMethodsv4/include/itkBSplineSyNImageRegistrationMethod.hxx#L342-L345)).  It's not so straightforward with the Gaussian smoothing in SyN.  However, I don't know if that non-binary functionality is accessible through the antsRegistration.cxx tool---I'd have to check.

**Comment by stnava** [comment]
if you want to alter the ITK code that phil mentioned, as an expt, then you
can see if it helps this situation.  you'd have to change it in ITKR then
reinstall both ITKR and ANTsR.

that's probably worth checking on rather than initiating the whole ITK
change process w/o doing so first.



brian
