### ISSUE TITLE
dynamic radius in mrvnrf?

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#75]
I want to propose an idea for mrvnrfs. Specifically, allowing dynamic radius neighborhood for each layer. For example, train RFs at one resolution with rad=2, and at the next resolution with rad=1. This would also allow for running same resolution but with different radiuses, e.g., mr=c(1,1) ) rad=c(2,1).

This is rather easy to implement. Question is, what do you think it is worth it?

Also, I want to remove the current request for radius to have the dimensions of the image, and have a single number indicating omnidirectional neighborhood. For example, rad=1 should mean, of course, radius=c(1,1,1) for 3D images.

In sum, the new radius parameter is a vector the same length as resolutions, not the same length of dimensions. This would mean that existing scripts will not work (although I can adapt it as a new parameter and play inside to see which parameter was selected by the user).

I think this is a worth change if not many people have started using mrvnrfs (I know only me and Brian).

Question 2: @stnava do you think running mrvnrfs with a final layer with radius=0 can bring something good? I.e. mr=c(6,4,2,1,1) with radiuses=c(1,1,1,1,0). This means the last RF has no neighborhood information, the voxel would still be strongly influenced by the features carried over from previous steps, but without the strong neighborhood information, perhaps allowing more small spatial deviations of a lesion prediction.

**Comment by stnava** [comment]
the ability to have a non-uniform radius i.e. ` rad=c(1,1,0) ` is valuable because of the commonality of anisotropic images.

your idea could be implemented in a  backward-compatible way but it would add some complexity to the code.   in general, it's not a good idea to replace valuable functionality with functionality that has no clear benefit.

re: Q2 - worth testing empirically but i do not think the accuracy of "ground truth" data would be able to measure any change in performance.

you can test both ideas empirically to see if they help/matter.

**Comment by dorianps** [comment]
Not worth pursuing here, will check later if a dynamic radius makes sense in mrvnrfs.
