### ISSUE TITLE
Feature request: concatenate motion correction + intersession registration

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#90]
I would like to add this to the list of possible things to have in ANTsR.

As you know, motion correction in fMRI is typically performed within the session, and multiple sessions are then registered together. If we do this in ANTsR, later sessions have two interpolations, for the moco and for the inter-session registration. Thus, we need a way to concatenate registration parameters with the output of antsRegistration. Right now there doesn't seem to be a way to do this.

I think the way SPM handles this issue is by changing only the headers, so that reslicing is done after all transforms are applied. ANTsR moco results, however, are already resliced.

**Comment by stnava** [comment]
Standard multisession motion correction in antsr uses only one
interpolation.  Why complicate things?

On Saturday, March 5, 2016, dorianps <notifications@github.com> wrote:

> I am would like to add this to the list of possible things to have in
> ANTsR.
>
> As you know, motion correction in fMRI is typically performed within the
> session, and multiple sessions are then registered together. If we do this
> in ANTsR, later sessions have two interpolations, for the moco and for the
> inter-session registration. Thus, we need a way to concatenate registration
> parameters with the output of antsRegistration. Right now there doesn't
> seem to be a way to do this.
>
> I think the way SPM handles this issue is by changing only the headers, so
> that reslicing is done after all transforms are applied. ANTsR moco
> results, however, are already resliced.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stnava/ANTsR/issues/90>.
>


-- 

brian

**Comment by dorianps** [comment]
Might have missed that. Which function does multisession?

Ty

**Comment by stnava** [comment]
Fmrinormalization

On Saturday, March 5, 2016, dorianps <notifications@github.com> wrote:

> Might have missed that. Which function does multisession?
>
> Ty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stnava/ANTsR/issues/90#issuecomment-192802130>.
>


-- 

brian

**Comment by dorianps** [comment]
fMRINormalization outputs the parameters of intra-session registration but the real registration is performed from each volume of 2nd session to the average of the 1st session. This means that moco_params do not even reflect the true registration that might have been performed on the data.

I think in general would be good to concatenate moco with other registrations, say i.e. to bring fMRI in template space with a single interpolation. Just an idea, but we can close this if not worth it.

**Comment by stnava** [comment]
there is some subtle detail here worth thinking about ... here are the points to consider:

* on the scale of registration, intrasubject intramodality registration is easy.  as long as the brain is not flipped or something like that, we should not worry about which target we use whether it is the first volume of the first session, the average of the first session or otherwise.

* fmrinormalization currently registers all sessions to the average of the first session

* however, because it is possible that the subject moved substantially between sessions, we compute moco_params from within-session registration.  so these parameters are relative to the session, not to the fixed target.   statistically, i think this makes more sense than using the parameters to the first session, which is arbitrary.

* this allows moco_params to be used consistently as statistical regressors.

* finally, to go to the *group template* (eg mni space), 2 interpolations are currently used.   someone may want to modify  antsrMotionCorr if they want to avoid that.   it's fairly trivial to implement but the documentation has to be clear and the implementation should be backward compatible with flow-through via fmrinormalization.
